services:
  master0:
    ports:
      - 6079:6079
    build:
      context: ./redisnode
      args:
        - REDIS_PORT=6079

  replica0:
    ports:
      - 6080:6080
    build:
      context: ./redisnode
      args:
        - REDIS_PORT=6080
    depends_on:
      - master0

  master1:
    ports:
      - 6179:6179
    build:
      context: ./redisnode
      args:
        - REDIS_PORT=6179
    
  replica1:
    ports:
      - 6180:6180
    build:
      context: ./redisnode
      args:
        - REDIS_PORT=6180
    depends_on:
      - master1

  master2:
    ports:
      - 6279:6279
    build:
      context: ./redisnode
      args:
        - REDIS_PORT=6279

  replica2:
    ports:
      - 6280:6280
    build:
      context: ./redisnode
      args:
        - REDIS_PORT=6280
    depends_on:
      - master2

  cluster-setup:
    network_mode: host
    build: ./cluster-setup
    depends_on:
      - master0
      - master1
      - master2
      - replica0
      - replica1
      - replica2

  online-buddy1:
    ports:
      - 3000:3000
    build:
      context: .
      args:
        - REDIS_CONNECTION_URL=master0:6079
        - API_PORT=3000

  online-buddy2:
    ports:
      - 3001:3001
    build:
      context: .
      args:
        - REDIS_CONNECTION_URL=master1:6179
        - API_PORT=3001